// <auto-generated />
using System;
using EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityFramework.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260523121252_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.GearItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DateOfPurchase")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ExpectedReturnDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("GearCategory")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InspectedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("LastInspection")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("Length")
                        .HasColumnType("int");

                    b.Property<int?>("LentByUserId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("LentDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("LentToUserId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ManufacturerExpiry")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("NextInspection")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ReturnedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("Sex")
                        .HasColumnType("int");

                    b.Property<int?>("Size")
                        .HasColumnType("int");

                    b.Property<int>("StorageLocation")
                        .HasColumnType("int");

                    b.Property<string>("ToughTag")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InspectedByUserId");

                    b.HasIndex("LentByUserId");

                    b.HasIndex("LentToUserId");

                    b.ToTable("GearItems");
                });

            modelBuilder.Entity("Domain.Entities.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GearItemId")
                        .HasColumnType("int");

                    b.Property<int?>("InspectedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("LentByUserId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("LentDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("LentToUserId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ReturnedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("GearItemId");

                    b.HasIndex("InspectedByUserId");

                    b.HasIndex("LentByUserId");

                    b.HasIndex("LentToUserId");

                    b.ToTable("Logbook");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MemberType")
                        .HasColumnType("int");

                    b.Property<int?>("OrderNo")
                        .HasColumnType("int");

                    b.Property<string>("Otp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartDate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Entities.GearItem", b =>
                {
                    b.HasOne("Domain.Entities.User", "InspectedByUser")
                        .WithMany()
                        .HasForeignKey("InspectedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.User", "LentByUser")
                        .WithMany()
                        .HasForeignKey("LentByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.User", "LentToUser")
                        .WithMany()
                        .HasForeignKey("LentToUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("InspectedByUser");

                    b.Navigation("LentByUser");

                    b.Navigation("LentToUser");
                });

            modelBuilder.Entity("Domain.Entities.Log", b =>
                {
                    b.HasOne("Domain.Entities.GearItem", "GearItem")
                        .WithMany()
                        .HasForeignKey("GearItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "InspectedByUser")
                        .WithMany()
                        .HasForeignKey("InspectedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.User", "LentByUser")
                        .WithMany()
                        .HasForeignKey("LentByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.User", "LentToUser")
                        .WithMany()
                        .HasForeignKey("LentToUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("GearItem");

                    b.Navigation("InspectedByUser");

                    b.Navigation("LentByUser");

                    b.Navigation("LentToUser");
                });
#pragma warning restore 612, 618
        }
    }
}
